env: standard
runtime: nodejs14

handlers:
  - url: /
    static_files: build/web/index.html
    upload: build/web/index.html
    secure: always
    redirect_http_response_code: 301

  - url: /(.*)
    static_files: build/web/\1
    upload: build/web/(.*)
    secure: always
    redirect_http_response_code: 301